global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'task-service'
    static_configs:
      - targets: ['task-service:8001']
  - job_name: 'scheduler-service'
    static_configs:
      - targets: ['scheduler-service:8001']
  - job_name: 'notifier-service'
    static_configs:
      - targets: ['notifier-service:8001']
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8001'] 
alerting:
 alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  - "alert_rules.yml"  # путь до файла с алертами